apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: api
  namespace: argocd
spec:
  generators:
    - list:
        elements:
          - image-tag: pr-1
  template:
    metadata:
      name: "api-{{image-tag}}"
    spec:
      project: default
      source:
        repoURL: https://github.com/nizar-i/example-argocd.git
        targetRevision: HEAD
        path: helm-charts/api
        helm:
          parameters:
            - name: "image.tag"
              value: "{{image-tag}}"
          valueFiles:
            - values.yaml
      destination:
        server: https://kubernetes.default.svc
        namespace: api
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
